schema: spec-driven
created: 2026-07-10
created_by: Hau-Hung Yang <43329288+Hardy1Yang@users.noreply.github.com>
created_with: claude
archived_by: Hau-Hung Yang <43329288+Hardy1Yang@users.noreply.github.com>
archived_at: 2026-07-10
